### PR TITLE
Add citation

### PR DESCRIPTION
**Pull request by sjanssen2**
I want to add the correct citation to the function `sepp`, such that it will be encoded in the produced artifacts. But I fail to pass Travis tests.

### CODE REVIEW

**Comment by sjanssen2** [comment]
current Travis error is and I don't know what to do about it. @thermokarst do you have any ideas?
```
The command "q2lint" exited with 0.
8.73s$ qiime dev refresh-cache
QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-env/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/dev.py", line 27, in refresh_cache
    import q2cli.cache
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/cache.py", line 301, in <module>
    CACHE = DeploymentCache()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2cli/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/q2_fragment_insertion-2018.4.0-py3.5.egg/q2_fragment_insertion/plugin_setup.py", line 21, in <module>
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/qiime2/core/cite.py", line 22, in load
    root = pkg_resources.resource_filename(package, '.')
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1137, in resource_filename
    self, resource_name
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1646, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1667, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'q2_fragment_insertion/.'
```

**Comment by thermokarst** [comment]
Hey @sjanssen2 I can take a look at this some time this week.

**Comment by thermokarst** [comment]
Hey @sjanssen2 - sorry I took so long to get to this. Anyway, this is a python packaging issue - the `package_data` isn't actually being included when installing. There are a handful of ways to solve this - the easiest is to declare[ `zip_safe=False` in `setup.py`](https://github.com/qiime2/q2-types/blob/353056c1b43b62e1288d597193c19a37ec8b1ab4/setup.py#L48). Testing locally that resolves the issue for me.

**Comment by sjanssen2** [comment]
@thermokarst don't worry about the delay. I am very thankful for your hint, it seems to work :-)

**Comment by sjanssen2** [comment]
Hi @wasade could you quickly review and eventually hit merge?

**Pull request merged**
